<?php

declare(strict_types=1);

namespace vixikhd\dragons\entity;

use pocketmine\block\Block;
use pocketmine\entity\Entity;
use pocketmine\entity\projectile\Throwable;
use pocketmine\math\RayTraceResult;
use pocketmine\Player;
use vixikhd\dragons\arena\DragonTargetManager;
use vixikhd\dragons\Dragons;
use vixikhd\dragons\effects\Effects;

/**
 * Class EggBait
 * @package vixikhd\dragons\entity
 */
class EggBait extends Throwable {

    public const NETWORK_ID = Entity::EGG;

    /**
     * @param Block $blockHit
     * @param RayTraceResult $hitResult
     */
    public function onHitBlock(Block $blockHit, RayTraceResult $hitResult): void {
        $player = $this->getOwningEntity();
        if(!$player instanceof Player) {
            return;
        }

        $arena = Dragons::getInstance()->getArenaByPlayer($player);
        $targetManager = $arena->dragonTargetManager;
        if(!$targetManager instanceof DragonTargetManager) {
            return;
        }

        Effects::spawnEffect(Effects::BAIT_SPIRAL, $blockHit->asPosition());
        $targetManager->addBait($blockHit->asVector3());
        parent::onHitBlock($blockHit, $hitResult); // TODO: Change the autogenerated stub
    }

}